name = "Lars Eggimann"
description = "Experimental Physicist, part time software developer, hobby game dev."
keywords = "Lars Eggimann, physics, experimentalist, software developer"
image = "me.webp"
theme = "dark"
primary_color = "#216e26"
text_align = "center"
gtag_id = "G-33WB8LVHR6"
base_url = "https://larseggimann.github.io/links"

[[sections]]
title = "Links"
description = "Look for me on these websites"
direction = "row"
item_style = "filled"
[[sections.items]]
title = "LinkedIn"
url = "https://www.linkedin.com/in/lars-eggimann-989189218/"
[[sections.items]]
title = "IEEE Xplore"
url = "https://ieeexplore.ieee.org/author/783226350881842"
[[sections.items]]
title = "ORCID"
url = "https://orcid.org/0009-0006-3460-2095"


[[sections]]
title = "My Projects"
description = "Here are some of my private projects"
direction = "column"
item_style = "outline"
[[sections.items]]
title = "Power Fetcher"
description = "A small NiceGUI application that crawls a power monitor on our network, logs and displays the data in a small web app"
url = "https://github.com/LarsEggimann/power-fetcher"
[[sections.items]]
title = "My GitHub"
description = "My GitHub profile with all my public projects"
url = "https://github.com/LarsEggimann"


